// this code is autogenerated, do not check it into to your code repository

// ref lib/graphmath/Quatern.ex:19
const beam = @import("beam");
const e = @import("erl_nif");
const std = @import("std");
const c = @cImport({
    @cInclude("math.h");
});

fn get_tuple(comptime T: type, term: beam.term) !T {
    const info = @typeInfo(T);
    const fields = info.Struct.fields;
    var arity: c_int = undefined;
    var ptr: [*c]const e.ErlNifTerm = undefined;
    if (e.enif_get_tuple(beam.context.env, term.v, &arity, &ptr) == 0) return error.ArgumentError;
    if (arity != fields.len) return error.ArgumentError;
    var result: T = undefined;
    inline for (fields, 0..) |field, i| {
        if (field.type == f64) {
            var val: f64 = undefined;
            if (e.enif_get_double(beam.context.env, ptr[i], &val) != 0) {
                @field(result, field.name) = val;
            } else {
                var ival: i64 = undefined;
                if (e.enif_get_int64(beam.context.env, ptr[i], &ival) != 0) {
                    @field(result, field.name) = @as(f64, @floatFromInt(ival));
                } else return error.ArgumentError;
            }
        } else {
            @field(result, field.name) = try beam.get(field.type, .{ .v = ptr[i] }, .{});
        }
    }
    return result;
}

pub fn identity_nif() beam.term {
    return beam.make(.{ 1.0, 0.0, 0.0, 0.0 }, .{});
}

pub fn zero_nif() beam.term {
    return beam.make(.{ 0.0, 0.0, 0.0, 0.0 }, .{});
}

pub fn from_axis_angle_nif(theta: f64, axis_term: beam.term) !beam.term {
    const axis = try get_tuple(struct { f64, f64, f64 }, axis_term);
    const half_theta = theta / 2.0;
    const ct = std.math.cos(half_theta);
    const st = std.math.sin(half_theta);
    return beam.make(.{ ct, st * axis.@"0", st * axis.@"1", st * axis.@"2" }, .{});
}

pub fn add_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64 }, b_term);
    return beam.make(.{ a.@"0" + b.@"0", a.@"1" + b.@"1", a.@"2" + b.@"2", a.@"3" + b.@"3" }, .{});
}

pub fn subtract_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64 }, b_term);
    return beam.make(.{ a.@"0" - b.@"0", a.@"1" - b.@"1", a.@"2" - b.@"2", a.@"3" - b.@"3" }, .{});
}

pub fn multiply_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"0" * b.@"0" - a.@"1" * b.@"1" - a.@"2" * b.@"2" - a.@"3" * b.@"3",
        a.@"0" * b.@"1" + a.@"1" * b.@"0" + a.@"2" * b.@"3" - a.@"3" * b.@"2",
        a.@"0" * b.@"2" + a.@"2" * b.@"0" + a.@"3" * b.@"1" - a.@"1" * b.@"3",
        a.@"0" * b.@"3" + a.@"3" * b.@"0" + a.@"1" * b.@"2" - a.@"2" * b.@"1",
    }, .{});
}

pub fn scale_nif(a_term: beam.term, s: f64) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"0" * s, a.@"1" * s, a.@"2" * s, a.@"3" * s }, .{});
}

pub fn get_roll_nif(a_term: beam.term) !f64 {
    const q = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const f_t_y = 2.0 * q.@"2";
    const f_t_z = 2.0 * q.@"3";
    return std.math.atan2(f_t_y * q.@"1" + f_t_z * q.@"0", 1.0 - (f_t_y * q.@"2" + f_t_z * q.@"3"));
}

pub fn get_pitch_nif(a_term: beam.term) !f64 {
    const q = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const f_t_x = 2.0 * q.@"1";
    const f_t_z = 2.0 * q.@"3";
    return std.math.atan2(f_t_z * q.@"2" + f_t_x * q.@"0", 1.0 - (f_t_x * q.@"1" + f_t_z * q.@"3"));
}

pub fn get_yaw_nif(a_term: beam.term) !f64 {
    const q = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const val1 = 2.0 * (q.@"3" * q.@"1" + q.@"2" * q.@"0");
    const val2 = 1.0 - 2.0 * (q.@"1" * q.@"1" + q.@"2" * q.@"2");
    return c.atan2(val1, val2);
}

pub fn to_rotation_matrix_33_nif(a_term: beam.term) !beam.term {
    const q = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const w = q.@"0"; const x = q.@"1"; const y = q.@"2"; const z = q.@"3";
    const f_tx = x + x; const f_ty = y + y; const f_tz = z + z;
    const f_t_wx = f_tx * w; const f_t_wy = f_ty * w; const f_t_wz = f_tz * w;
    const f_t_xx = f_tx * x; const f_t_xy = f_ty * x; const f_t_xz = f_tz * x;
    const f_t_yy = f_ty * y; const f_t_yz = f_tz * y; const f_t_zz = f_tz * z;
    return beam.make(.{
        1.0 - (f_t_yy + f_t_zz), f_t_xy - f_t_wz, f_t_xz + f_t_wy,
        f_t_xy + f_t_wz, 1.0 - (f_t_xx + f_t_zz), f_t_yz - f_t_wx,
        f_t_xz - f_t_wy, f_t_yz + f_t_wx, 1.0 - (f_t_xx + f_t_yy),
    }, .{});
}

pub fn to_rotation_matrix_44_nif(a_term: beam.term) !beam.term {
    const q = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const w = q.@"0"; const x = q.@"1"; const y = q.@"2"; const z = q.@"3";
    const f_tx = x + x; const f_ty = y + y; const f_tz = z + z;
    const f_t_wx = f_tx * w; const f_t_wy = f_ty * w; const f_t_wz = f_tz * w;
    const f_t_xx = f_tx * x; const f_t_xy = f_ty * x; const f_t_xz = f_tz * x;
    const f_t_yy = f_ty * y; const f_t_yz = f_tz * y; const f_t_zz = f_tz * z;
    return beam.make(.{
        1.0 - (f_t_yy + f_t_zz), f_t_xy - f_t_wz, f_t_xz + f_t_wy, 0.0,
        f_t_xy + f_t_wz, 1.0 - (f_t_xx + f_t_zz), f_t_yz - f_t_wx, 0.0,
        f_t_xz - f_t_wy, f_t_yz + f_t_wx, 1.0 - (f_t_xx + f_t_yy), 0.0,
        0.0, 0.0, 0.0, 1.0,
    }, .{});
}

pub fn dot_nif(a_term: beam.term, b_term: beam.term) !f64 {
    const a = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64 }, b_term);
    return a.@"0" * b.@"0" + a.@"1" * b.@"1" + a.@"2" * b.@"2" + a.@"3" * b.@"3";
}

pub fn norm_nif(a_term: beam.term) !f64 {
    const a = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    return std.math.sqrt(a.@"0" * a.@"0" + a.@"1" * a.@"1" + a.@"2" * a.@"2" + a.@"3" * a.@"3");
}

pub fn normalize_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const mag = std.math.sqrt(a.@"0" * a.@"0" + a.@"1" * a.@"1" + a.@"2" * a.@"2" + a.@"3" * a.@"3");
    if (mag > 0) {
        const inv_mag = 1.0 / mag;
        return beam.make(.{ a.@"0" * inv_mag, a.@"1" * inv_mag, a.@"2" * inv_mag, a.@"3" * inv_mag }, .{});
    } else {
        return beam.make(.{ 0.0, 0.0, 0.0, 0.0 }, .{});
    }
}

pub fn inverse_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const f_norm = a.@"0" * a.@"0" + a.@"1" * a.@"1" + a.@"2" * a.@"2" + a.@"3" * a.@"3";
    if (f_norm > 0.0) {
        const f_inv_norm = 1.0 / f_norm;
        return beam.make(.{ a.@"0" * f_inv_norm, -a.@"1" * f_inv_norm, -a.@"2" * f_inv_norm, -a.@"3" * f_inv_norm }, .{});
    } else {
        return beam.make(.{ 0.0, 0.0, 0.0, 0.0 }, .{});
    }
}

pub fn slerp_nif(a_term: beam.term, b_term: beam.term, t: f64) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64 }, b_term);
    const f_cos = a.@"0" * b.@"0" + a.@"1" * b.@"1" + a.@"2" * b.@"2" + a.@"3" * b.@"3";

    if (@abs(f_cos) < 1.0 - 1.0e-03) {
        const f_sin = std.math.sqrt(1.0 - f_cos * f_cos);
        const f_angle = std.math.atan2(f_sin, f_cos);
        const f_inv_sin = 1.0 / f_sin;
        const f_coeff0 = std.math.sin((1.0 - t) * f_angle) * f_inv_sin;
        const f_coeff1 = std.math.sin(t * f_angle) * f_inv_sin;

        const res_w = a.@"0" * f_coeff0 + b.@"0" * f_coeff1;
        const res_x = a.@"1" * f_coeff0 + b.@"1" * f_coeff1;
        const res_y = a.@"2" * f_coeff0 + b.@"2" * f_coeff1;
        const res_z = a.@"3" * f_coeff0 + b.@"3" * f_coeff1;

        const mag = std.math.sqrt(res_w*res_w + res_x*res_x + res_y*res_y + res_z*res_z);
        const inv_mag = 1.0 / mag;
        return beam.make(.{ res_w * inv_mag, res_x * inv_mag, res_y * inv_mag, res_z * inv_mag }, .{});
    } else {
        const res_w = a.@"0" * (1.0 - t) + b.@"0" * t;
        const res_x = a.@"1" * (1.0 - t) + b.@"1" * t;
        const res_y = a.@"2" * (1.0 - t) + b.@"2" * t;
        const res_z = a.@"3" * (1.0 - t) + b.@"3" * t;

        const mag = std.math.sqrt(res_w*res_w + res_x*res_x + res_y*res_y + res_z*res_z);
        const inv_mag = 1.0 / mag;
        return beam.make(.{ res_w * inv_mag, res_x * inv_mag, res_y * inv_mag, res_z * inv_mag }, .{});
    }
}

pub fn transform_vector_nif(q_term: beam.term, v_term: beam.term) !beam.term {
    const q = try get_tuple(struct { f64, f64, f64, f64 }, q_term);
    const v = try get_tuple(struct { f64, f64, f64 }, v_term);
    const qw = q.@"0"; const qx = q.@"1"; const qy = q.@"2"; const qz = q.@"3";
    const vx = v.@"0"; const vy = v.@"1"; const vz = v.@"2";

    const dot_uv = qx * vx + qy * vy + qz * vz;
    const two_dot_uv = 2.0 * dot_uv;
    const dot_uu = qx * qx + qy * qy + qz * qz;
    const v_scalar = qw * qw - dot_uu;
    const two_qw = 2.0 * qw;

    return beam.make(.{
        two_dot_uv * qx + v_scalar * vx + two_qw * (qy * vz - qz * vy),
        two_dot_uv * qy + v_scalar * vy + two_qw * (qz * vx - qx * vz),
        two_dot_uv * qz + v_scalar * vz + two_qw * (qx * vy - qy * vx)
    }, .{});
}

pub fn from_rotation_matrix_nif(mat_term: beam.term) !beam.term {
    const mat = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, mat_term);
    const a11 = mat.@"0"; const a12 = mat.@"1"; const a13 = mat.@"2";
    const a21 = mat.@"3"; const a22 = mat.@"4"; const a23 = mat.@"5";
    const a31 = mat.@"6"; const a32 = mat.@"7"; const a33 = mat.@"8";

    const f_trace = a11 + a22 + a33;

    if (f_trace > 0.0) {
        const f_root = std.math.sqrt(f_trace + 1.0);
        const w = 0.5 * f_root;
        const s = 0.5 / f_root;
        return beam.make(.{ w, (a32 - a23) * s, (a13 - a31) * s, (a21 - a12) * s }, .{});
    } else {
        var i: usize = 0;
        if (a22 > a11) i = 1;
        if (i == 0) { if (a33 > a11) i = 2; } else { if (a33 > a22) i = 2; }

        const i_next = [3]usize{ 1, 2, 0 };
        const j = i_next[i];
        const k = i_next[j];

        const m = [9]f64{ a11, a12, a13, a21, a22, a23, a31, a32, a33 };
        const f_root = std.math.sqrt(m[i * 3 + i] - m[j * 3 + j] - m[k * 3 + k] + 1.0);

        var apk_quat = [3]f64{ 0.0, 0.0, 0.0 };
        apk_quat[i] = 0.5 * f_root;
        const s = 0.5 / f_root;
        apk_quat[j] = (m[j * 3 + i] + m[i * 3 + j]) * s;
        apk_quat[k] = (m[k * 3 + i] + m[i * 3 + k]) * s;

        return beam.make(.{ apk_quat[0], apk_quat[1], apk_quat[2], (m[k * 3 + j] - m[j * 3 + k]) * s }, .{});
    }
}

pub fn integrate_nif(q_term: beam.term, omega_term: beam.term, dt: f64) !beam.term {
    const q = try get_tuple(struct { f64, f64, f64, f64 }, q_term);
    const omega = try get_tuple(struct { f64, f64, f64 }, omega_term);

    const half_dt = dt * 0.5;
    const theta_x = omega.@"0" * half_dt;
    const theta_y = omega.@"1" * half_dt;
    const theta_z = omega.@"2" * half_dt;

    const theta_mag_sq = theta_x * theta_x + theta_y * theta_y + theta_z * theta_z;

    var delta_q_w: f64 = undefined;
    var s: f64 = undefined;

    if (theta_mag_sq * theta_mag_sq / 24.0 < 5.96e-08) {
        delta_q_w = 1.0 - theta_mag_sq / 2.0;
        s = 1.0 - theta_mag_sq / 6.0;
    } else {
        const theta_mag = std.math.sqrt(theta_mag_sq);
        delta_q_w = std.math.cos(theta_mag);
        s = std.math.sin(theta_mag) / theta_mag;
    }

    const dq_w = delta_q_w;
    const dq_x = theta_x * s;
    const dq_y = theta_y * s;
    const dq_z = theta_z * s;

    // Multiply dq * q
    const res_w = dq_w * q.@"0" - dq_x * q.@"1" - dq_y * q.@"2" - dq_z * q.@"3";
    const res_x = dq_w * q.@"1" + dq_x * q.@"0" + dq_y * q.@"3" - dq_z * q.@"2";
    const res_y = dq_w * q.@"2" + dq_y * q.@"0" + dq_z * q.@"1" - dq_x * q.@"3";
    const res_z = dq_w * q.@"3" + dq_z * q.@"0" + dq_x * q.@"2" - dq_y * q.@"1";

    const mag = std.math.sqrt(res_w*res_w + res_x*res_x + res_y*res_y + res_z*res_z);
    const inv_mag = if (mag > 0) 1.0 / mag else 1.0;
    return beam.make(.{ res_w * inv_mag, res_x * inv_mag, res_y * inv_mag, res_z * inv_mag }, .{});
}
