// this code is autogenerated, do not check it into to your code repository

// ref lib/graphmath/Mat44.ex:16
const beam = @import("beam");
const e = @import("erl_nif");
const std = @import("std");

fn get_tuple(comptime T: type, term: beam.term) !T {
    const info = @typeInfo(T);
    const fields = info.Struct.fields;
    var arity: c_int = undefined;
    var ptr: [*c]const e.ErlNifTerm = undefined;
    if (e.enif_get_tuple(beam.context.env, term.v, &arity, &ptr) == 0) return error.ArgumentError;
    if (arity != fields.len) return error.ArgumentError;
    var result: T = undefined;
    inline for (fields, 0..) |field, i| {
        if (field.type == f64) {
            var val: f64 = undefined;
            if (e.enif_get_double(beam.context.env, ptr[i], &val) != 0) {
                @field(result, field.name) = val;
            } else {
                var ival: i64 = undefined;
                if (e.enif_get_int64(beam.context.env, ptr[i], &ival) != 0) {
                    @field(result, field.name) = @as(f64, @floatFromInt(ival));
                } else return error.ArgumentError;
            }
        } else {
            @field(result, field.name) = try beam.get(field.type, .{ .v = ptr[i] }, .{});
        }
    }
    return result;
}

pub fn identity_nif() beam.term {
    return beam.make(.{
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 1.0,
    }, .{});
}

pub fn zero_nif() beam.term {
    return beam.make(.{
        0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0,
    }, .{});
}

pub fn add_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"0" + b.@"0", a.@"1" + b.@"1", a.@"2" + b.@"2", a.@"3" + b.@"3",
        a.@"4" + b.@"4", a.@"5" + b.@"5", a.@"6" + b.@"6", a.@"7" + b.@"7",
        a.@"8" + b.@"8", a.@"9" + b.@"9", a.@"10" + b.@"10", a.@"11" + b.@"11",
        a.@"12" + b.@"12", a.@"13" + b.@"13", a.@"14" + b.@"14", a.@"15" + b.@"15",
    }, .{});
}

pub fn subtract_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"0" - b.@"0", a.@"1" - b.@"1", a.@"2" - b.@"2", a.@"3" - b.@"3",
        a.@"4" - b.@"4", a.@"5" - b.@"5", a.@"6" - b.@"6", a.@"7" - b.@"7",
        a.@"8" - b.@"8", a.@"9" - b.@"9", a.@"10" - b.@"10", a.@"11" - b.@"11",
        a.@"12" - b.@"12", a.@"13" - b.@"13", a.@"14" - b.@"14", a.@"15" - b.@"15",
    }, .{});
}

pub fn scale_nif(a_term: beam.term, k: f64) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{
        a.@"0" * k, a.@"1" * k, a.@"2" * k, a.@"3" * k,
        a.@"4" * k, a.@"5" * k, a.@"6" * k, a.@"7" * k,
        a.@"8" * k, a.@"9" * k, a.@"10" * k, a.@"11" * k,
        a.@"12" * k, a.@"13" * k, a.@"14" * k, a.@"15" * k,
    }, .{});
}

pub fn make_scale1_nif(k: f64) beam.term {
    return beam.make(.{
        k, 0.0, 0.0, 0.0,
        0.0, k, 0.0, 0.0,
        0.0, 0.0, k, 0.0,
        0.0, 0.0, 0.0, k,
    }, .{});
}

pub fn make_scale4_nif(sx: f64, sy: f64, sz: f64, sw: f64) beam.term {
    return beam.make(.{
        sx, 0.0, 0.0, 0.0,
        0.0, sy, 0.0, 0.0,
        0.0, 0.0, sz, 0.0,
        0.0, 0.0, 0.0, sw,
    }, .{});
}

pub fn make_translate_nif(tx: f64, ty: f64, tz: f64) beam.term {
    return beam.make(.{
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0,
        tx, ty, tz, 1.0,
    }, .{});
}

pub fn make_rotate_x_nif(theta: f64) beam.term {
    const st = std.math.sin(theta);
    const ct = std.math.cos(theta);
    return beam.make(.{
        1.0, 0.0, 0.0, 0.0,
        0.0, ct, st, 0.0,
        0.0, -st, ct, 0.0,
        0.0, 0.0, 0.0, 1.0,
    }, .{});
}

pub fn make_rotate_y_nif(theta: f64) beam.term {
    const st = std.math.sin(theta);
    const ct = std.math.cos(theta);
    return beam.make(.{
        ct, 0.0, st, 0.0,
        0.0, 1.0, 0.0, 0.0,
        -st, 0.0, ct, 0.0,
        0.0, 0.0, 0.0, 1.0,
    }, .{});
}

pub fn make_rotate_z_nif(theta: f64) beam.term {
    const st = std.math.sin(theta);
    const ct = std.math.cos(theta);
    return beam.make(.{
        ct, st, 0.0, 0.0,
        -st, ct, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 1.0,
    }, .{});
}

pub fn multiply_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"0" * b.@"0" + a.@"1" * b.@"4" + a.@"2" * b.@"8" + a.@"3" * b.@"12",
        a.@"0" * b.@"1" + a.@"1" * b.@"5" + a.@"2" * b.@"9" + a.@"3" * b.@"13",
        a.@"0" * b.@"2" + a.@"1" * b.@"6" + a.@"2" * b.@"10" + a.@"3" * b.@"14",
        a.@"0" * b.@"3" + a.@"1" * b.@"7" + a.@"2" * b.@"11" + a.@"3" * b.@"15",
        a.@"4" * b.@"0" + a.@"5" * b.@"4" + a.@"6" * b.@"8" + a.@"7" * b.@"12",
        a.@"4" * b.@"1" + a.@"5" * b.@"5" + a.@"6" * b.@"9" + a.@"7" * b.@"13",
        a.@"4" * b.@"2" + a.@"5" * b.@"6" + a.@"6" * b.@"10" + a.@"7" * b.@"14",
        a.@"4" * b.@"3" + a.@"5" * b.@"7" + a.@"6" * b.@"11" + a.@"7" * b.@"15",
        a.@"8" * b.@"0" + a.@"9" * b.@"4" + a.@"10" * b.@"8" + a.@"11" * b.@"12",
        a.@"8" * b.@"1" + a.@"9" * b.@"5" + a.@"10" * b.@"9" + a.@"11" * b.@"13",
        a.@"8" * b.@"2" + a.@"9" * b.@"6" + a.@"10" * b.@"10" + a.@"11" * b.@"14",
        a.@"8" * b.@"3" + a.@"9" * b.@"7" + a.@"10" * b.@"11" + a.@"11" * b.@"15",
        a.@"12" * b.@"0" + a.@"13" * b.@"4" + a.@"14" * b.@"8" + a.@"15" * b.@"12",
        a.@"12" * b.@"1" + a.@"13" * b.@"5" + a.@"14" * b.@"9" + a.@"15" * b.@"13",
        a.@"12" * b.@"2" + a.@"13" * b.@"6" + a.@"14" * b.@"10" + a.@"15" * b.@"14",
        a.@"12" * b.@"3" + a.@"13" * b.@"7" + a.@"14" * b.@"11" + a.@"15" * b.@"15",
    }, .{});
}

pub fn multiply_transpose_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"0" * b.@"0" + a.@"1" * b.@"1" + a.@"2" * b.@"2" + a.@"3" * b.@"3",
        a.@"0" * b.@"4" + a.@"1" * b.@"5" + a.@"2" * b.@"6" + a.@"3" * b.@"7",
        a.@"0" * b.@"8" + a.@"1" * b.@"9" + a.@"2" * b.@"10" + a.@"3" * b.@"11",
        a.@"0" * b.@"12" + a.@"1" * b.@"13" + a.@"2" * b.@"14" + a.@"3" * b.@"15",
        a.@"4" * b.@"0" + a.@"5" * b.@"1" + a.@"6" * b.@"2" + a.@"7" * b.@"3",
        a.@"4" * b.@"4" + a.@"5" * b.@"5" + a.@"6" * b.@"6" + a.@"7" * b.@"7",
        a.@"4" * b.@"8" + a.@"5" * b.@"9" + a.@"6" * b.@"10" + a.@"7" * b.@"11",
        a.@"4" * b.@"12" + a.@"5" * b.@"13" + a.@"6" * b.@"14" + a.@"7" * b.@"15",
        a.@"8" * b.@"0" + a.@"9" * b.@"1" + a.@"10" * b.@"2" + a.@"11" * b.@"3",
        a.@"8" * b.@"4" + a.@"9" * b.@"5" + a.@"10" * b.@"6" + a.@"11" * b.@"7",
        a.@"8" * b.@"8" + a.@"9" * b.@"9" + a.@"10" * b.@"10" + a.@"11" * b.@"11",
        a.@"8" * b.@"12" + a.@"9" * b.@"13" + a.@"10" * b.@"14" + a.@"11" * b.@"15",
        a.@"12" * b.@"0" + a.@"13" * b.@"1" + a.@"14" * b.@"2" + a.@"15" * b.@"3",
        a.@"12" * b.@"4" + a.@"13" * b.@"5" + a.@"14" * b.@"6" + a.@"15" * b.@"7",
        a.@"12" * b.@"8" + a.@"13" * b.@"9" + a.@"14" * b.@"10" + a.@"15" * b.@"11",
        a.@"12" * b.@"12" + a.@"13" * b.@"13" + a.@"14" * b.@"14" + a.@"15" * b.@"15",
    }, .{});
}

pub fn column0_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"0", a.@"4", a.@"8", a.@"12" }, .{});
}

pub fn column1_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"1", a.@"5", a.@"9", a.@"13" }, .{});
}

pub fn column2_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"2", a.@"6", a.@"10", a.@"14" }, .{});
}

pub fn column3_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"3", a.@"7", a.@"11", a.@"15" }, .{});
}

pub fn row0_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"0", a.@"1", a.@"2", a.@"3" }, .{});
}

pub fn row1_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"4", a.@"5", a.@"6", a.@"7" }, .{});
}

pub fn row2_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"8", a.@"9", a.@"10", a.@"11" }, .{});
}

pub fn row3_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"12", a.@"13", a.@"14", a.@"15" }, .{});
}

pub fn diag_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"0", a.@"5", a.@"10", a.@"15" }, .{});
}

pub fn apply_nif(a_term: beam.term, v_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const v = try get_tuple(struct { f64, f64, f64, f64 }, v_term);
    return beam.make(.{
        a.@"0" * v.@"0" + a.@"1" * v.@"1" + a.@"2" * v.@"2" + a.@"3" * v.@"3",
        a.@"4" * v.@"0" + a.@"5" * v.@"1" + a.@"6" * v.@"2" + a.@"7" * v.@"3",
        a.@"8" * v.@"0" + a.@"9" * v.@"1" + a.@"10" * v.@"2" + a.@"11" * v.@"3",
        a.@"12" * v.@"0" + a.@"13" * v.@"1" + a.@"14" * v.@"2" + a.@"15" * v.@"3",
    }, .{});
}

pub fn apply_transpose_nif(a_term: beam.term, v_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const v = try get_tuple(struct { f64, f64, f64, f64 }, v_term);
    return beam.make(.{
        a.@"0" * v.@"0" + a.@"4" * v.@"1" + a.@"8" * v.@"2" + a.@"12" * v.@"3",
        a.@"1" * v.@"0" + a.@"5" * v.@"1" + a.@"9" * v.@"2" + a.@"13" * v.@"3",
        a.@"2" * v.@"0" + a.@"6" * v.@"1" + a.@"10" * v.@"2" + a.@"14" * v.@"3",
        a.@"3" * v.@"0" + a.@"7" * v.@"1" + a.@"11" * v.@"2" + a.@"15" * v.@"3",
    }, .{});
}

pub fn transform_point_nif(a_term: beam.term, v_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const v = try get_tuple(struct { f64, f64, f64 }, v_term);
    return beam.make(.{
        a.@"0" * v.@"0" + a.@"4" * v.@"1" + a.@"8" * v.@"2" + a.@"12",
        a.@"1" * v.@"0" + a.@"5" * v.@"1" + a.@"9" * v.@"2" + a.@"13",
        a.@"2" * v.@"0" + a.@"6" * v.@"1" + a.@"10" * v.@"2" + a.@"14",
    }, .{});
}

pub fn transform_vector_nif(a_term: beam.term, v_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const v = try get_tuple(struct { f64, f64, f64 }, v_term);
    return beam.make(.{
        a.@"0" * v.@"0" + a.@"4" * v.@"1" + a.@"8" * v.@"2",
        a.@"1" * v.@"0" + a.@"5" * v.@"1" + a.@"9" * v.@"2",
        a.@"2" * v.@"0" + a.@"6" * v.@"1" + a.@"10" * v.@"2",
    }, .{});
}

pub fn inverse_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const m00 = a.@"0"; const m01 = a.@"1"; const m02 = a.@"2"; const m03 = a.@"3";
    const m10 = a.@"4"; const m11 = a.@"5"; const m12 = a.@"6"; const m13 = a.@"7";
    const m20 = a.@"8"; const m21 = a.@"9"; const m22 = a.@"10"; const m23 = a.@"11";
    const m30 = a.@"12"; const m31 = a.@"13"; const m32 = a.@"14"; const m33 = a.@"15";

    var v0 = m20 * m31 - m21 * m30;
    var v1 = m20 * m32 - m22 * m30;
    var v2 = m20 * m33 - m23 * m30;
    var v3 = m21 * m32 - m22 * m31;
    var v4 = m21 * m33 - m23 * m31;
    var v5 = m22 * m33 - m23 * m32;

    const t00 = (v5 * m11 - v4 * m12 + v3 * m13);
    const t10 = -(v5 * m10 - v2 * m12 + v1 * m13);
    const t20 = (v4 * m10 - v2 * m11 + v0 * m13);
    const t30 = -(v3 * m10 - v1 * m11 + v0 * m12);

    const f_det = t00 * m00 + t10 * m01 + t20 * m02 + t30 * m03;
    if (f_det == 0.0) return error.ArgumentError;

    const inv_det = 1.0 / f_det;

    const d00 = t00 * inv_det;
    const d10 = t10 * inv_det;
    const d20 = t20 * inv_det;
    const d30 = t30 * inv_det;

    const d01 = -(v5 * m01 - v4 * m02 + v3 * m03) * inv_det;
    const d11 = (v5 * m00 - v2 * m02 + v1 * m03) * inv_det;
    const d21 = -(v4 * m00 - v2 * m01 + v0 * m03) * inv_det;
    const d31 = (v3 * m00 - v1 * m01 + v0 * m02) * inv_det;

    v0 = m10 * m31 - m11 * m30;
    v1 = m10 * m32 - m12 * m30;
    v2 = m10 * m33 - m13 * m30;
    v3 = m11 * m32 - m12 * m31;
    v4 = m11 * m33 - m13 * m31;
    v5 = m12 * m33 - m13 * m32;

    const d02 = (v5 * m01 - v4 * m02 + v3 * m03) * inv_det;
    const d12 = -(v5 * m00 - v2 * m02 + v1 * m03) * inv_det;
    const d22 = (v4 * m00 - v2 * m01 + v0 * m03) * inv_det;
    const d32 = -(v3 * m00 - v1 * m01 + v0 * m02) * inv_det;

    v0 = m21 * m10 - m20 * m11;
    v1 = m22 * m10 - m20 * m12;
    v2 = m23 * m10 - m20 * m13;
    v3 = m22 * m11 - m21 * m12;
    v4 = m23 * m11 - m21 * m13;
    v5 = m23 * m12 - m22 * m13;

    const d03 = -(v5 * m01 - v4 * m02 + v3 * m03) * inv_det;
    const d13 = (v5 * m00 - v2 * m02 + v1 * m03) * inv_det;
    const d23 = -(v4 * m00 - v2 * m01 + v0 * m03) * inv_det;
    const d33 = (v3 * m00 - v1 * m01 + v0 * m02) * inv_det;

    return beam.make(.{d00, d01, d02, d03, d10, d11, d12, d13, d20, d21, d22, d23, d30, d31, d32, d33}, .{});
}
