// this code is autogenerated, do not check it into to your code repository

// ref lib/graphmath/Mat33.ex:14
const beam = @import("beam");
const e = @import("erl_nif");
const std = @import("std");

fn get_tuple(comptime T: type, term: beam.term) !T {
    const info = @typeInfo(T);
    const fields = info.Struct.fields;
    var arity: c_int = undefined;
    var ptr: [*c]const e.ErlNifTerm = undefined;
    if (e.enif_get_tuple(beam.context.env, term.v, &arity, &ptr) == 0) return error.ArgumentError;
    if (arity != fields.len) return error.ArgumentError;
    var result: T = undefined;
    inline for (fields, 0..) |field, i| {
        if (field.type == f64) {
            var val: f64 = undefined;
            if (e.enif_get_double(beam.context.env, ptr[i], &val) != 0) {
                @field(result, field.name) = val;
            } else {
                var ival: i64 = undefined;
                if (e.enif_get_int64(beam.context.env, ptr[i], &ival) != 0) {
                    @field(result, field.name) = @as(f64, @floatFromInt(ival));
                } else return error.ArgumentError;
            }
        } else {
            @field(result, field.name) = try beam.get(field.type, .{ .v = ptr[i] }, .{});
        }
    }
    return result;
}

pub fn identity_nif() beam.term {
    return beam.make(.{ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 }, .{});
}

pub fn zero_nif() beam.term {
    return beam.make(.{ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, .{});
}

pub fn add_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"0" + b.@"0", a.@"1" + b.@"1", a.@"2" + b.@"2",
        a.@"3" + b.@"3", a.@"4" + b.@"4", a.@"5" + b.@"5",
        a.@"6" + b.@"6", a.@"7" + b.@"7", a.@"8" + b.@"8",
    }, .{});
}

pub fn subtract_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"0" - b.@"0", a.@"1" - b.@"1", a.@"2" - b.@"2",
        a.@"3" - b.@"3", a.@"4" - b.@"4", a.@"5" - b.@"5",
        a.@"6" - b.@"6", a.@"7" - b.@"7", a.@"8" - b.@"8",
    }, .{});
}

pub fn scale_nif(a_term: beam.term, k: f64) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{
        a.@"0" * k, a.@"1" * k, a.@"2" * k,
        a.@"3" * k, a.@"4" * k, a.@"5" * k,
        a.@"6" * k, a.@"7" * k, a.@"8" * k,
    }, .{});
}

pub fn make_scale1_nif(k: f64) beam.term {
    return beam.make(.{ k, 0.0, 0.0, 0.0, k, 0.0, 0.0, 0.0, k }, .{});
}

pub fn make_scale3_nif(sx: f64, sy: f64, sz: f64) beam.term {
    return beam.make(.{ sx, 0.0, 0.0, 0.0, sy, 0.0, 0.0, 0.0, sz }, .{});
}

pub fn make_translate_nif(tx: f64, ty: f64) beam.term {
    return beam.make(.{ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, tx, ty, 1.0 }, .{});
}

pub fn make_rotate_nif(theta: f64) beam.term {
    const st = std.math.sin(theta);
    const ct = std.math.cos(theta);
    return beam.make(.{ ct, st, 0.0, -st, ct, 0.0, 0.0, 0.0, 1.0 }, .{});
}

pub fn multiply_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"0" * b.@"0" + a.@"1" * b.@"3" + a.@"2" * b.@"6",
        a.@"0" * b.@"1" + a.@"1" * b.@"4" + a.@"2" * b.@"7",
        a.@"0" * b.@"2" + a.@"1" * b.@"5" + a.@"2" * b.@"8",
        a.@"3" * b.@"0" + a.@"4" * b.@"3" + a.@"5" * b.@"6",
        a.@"3" * b.@"1" + a.@"4" * b.@"4" + a.@"5" * b.@"7",
        a.@"3" * b.@"2" + a.@"4" * b.@"5" + a.@"5" * b.@"8",
        a.@"6" * b.@"0" + a.@"7" * b.@"3" + a.@"8" * b.@"6",
        a.@"6" * b.@"1" + a.@"7" * b.@"4" + a.@"8" * b.@"7",
        a.@"6" * b.@"2" + a.@"7" * b.@"5" + a.@"8" * b.@"8",
    }, .{});
}

pub fn multiply_transpose_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"0" * b.@"0" + a.@"1" * b.@"1" + a.@"2" * b.@"2",
        a.@"0" * b.@"3" + a.@"1" * b.@"4" + a.@"2" * b.@"5",
        a.@"0" * b.@"6" + a.@"1" * b.@"7" + a.@"2" * b.@"8",
        a.@"3" * b.@"0" + a.@"4" * b.@"1" + a.@"5" * b.@"2",
        a.@"3" * b.@"3" + a.@"4" * b.@"4" + a.@"5" * b.@"5",
        a.@"3" * b.@"6" + a.@"4" * b.@"7" + a.@"5" * b.@"8",
        a.@"6" * b.@"0" + a.@"7" * b.@"1" + a.@"8" * b.@"2",
        a.@"6" * b.@"3" + a.@"7" * b.@"4" + a.@"8" * b.@"5",
        a.@"6" * b.@"6" + a.@"7" * b.@"7" + a.@"8" * b.@"8",
    }, .{});
}

pub fn column0_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"0", a.@"3", a.@"6" }, .{});
}

pub fn column1_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"1", a.@"4", a.@"7" }, .{});
}

pub fn column2_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"2", a.@"5", a.@"8" }, .{});
}

pub fn row0_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"0", a.@"1", a.@"2" }, .{});
}

pub fn row1_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"3", a.@"4", a.@"5" }, .{});
}

pub fn row2_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"6", a.@"7", a.@"8" }, .{});
}

pub fn diag_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"0", a.@"4", a.@"8" }, .{});
}

pub fn apply_nif(a_term: beam.term, v_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const v = try get_tuple(struct { f64, f64, f64 }, v_term);
    return beam.make(.{
        a.@"0" * v.@"0" + a.@"1" * v.@"1" + a.@"2" * v.@"2",
        a.@"3" * v.@"0" + a.@"4" * v.@"1" + a.@"5" * v.@"2",
        a.@"6" * v.@"0" + a.@"7" * v.@"1" + a.@"8" * v.@"2",
    }, .{});
}

pub fn apply_transpose_nif(a_term: beam.term, v_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const v = try get_tuple(struct { f64, f64, f64 }, v_term);
    return beam.make(.{
        a.@"0" * v.@"0" + a.@"3" * v.@"1" + a.@"6" * v.@"2",
        a.@"1" * v.@"0" + a.@"4" * v.@"1" + a.@"7" * v.@"2",
        a.@"2" * v.@"0" + a.@"5" * v.@"1" + a.@"8" * v.@"2",
    }, .{});
}

pub fn transform_point_nif(a_term: beam.term, v_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const v = try get_tuple(struct { f64, f64 }, v_term);
    return beam.make(.{
        a.@"0" * v.@"0" + a.@"3" * v.@"1" + a.@"6",
        a.@"1" * v.@"0" + a.@"4" * v.@"1" + a.@"7",
    }, .{});
}

pub fn transform_vector_nif(a_term: beam.term, v_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const v = try get_tuple(struct { f64, f64 }, v_term);
    return beam.make(.{
        a.@"0" * v.@"0" + a.@"3" * v.@"1",
        a.@"1" * v.@"0" + a.@"4" * v.@"1",
    }, .{});
}

pub fn inverse_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64, f64, f64, f64, f64, f64, f64 }, a_term);
    const a00 = a.@"0"; const a01 = a.@"1"; const a02 = a.@"2";
    const a10 = a.@"3"; const a11 = a.@"4"; const a12 = a.@"5";
    const a20 = a.@"6"; const a21 = a.@"7"; const a22 = a.@"8";

    const v00 = a11 * a22 - a12 * a21;
    const v01 = a02 * a21 - a01 * a22;
    const v02 = a01 * a12 - a02 * a11;
    const v10 = a12 * a20 - a10 * a22;
    const v11 = a00 * a22 - a02 * a20;
    const v12 = a02 * a10 - a00 * a12;
    const v20 = a10 * a21 - a11 * a20;
    const v21 = a01 * a20 - a00 * a21;
    const v22 = a00 * a11 - a01 * a10;

    const f_det = a00 * v00 + a01 * v10 + a02 * v20;
    if (f_det == 0.0) return error.ArgumentError;

    const f_inv_det = 1.0 / f_det;

    return beam.make(.{
        v00 * f_inv_det, v01 * f_inv_det, v02 * f_inv_det,
        v10 * f_inv_det, v11 * f_inv_det, v12 * f_inv_det,
        v20 * f_inv_det, v21 * f_inv_det, v22 * f_inv_det,
    }, .{});
}
