// this code is autogenerated, do not check it into to your code repository

// ref lib/graphmath/Vec3.ex:13
const beam = @import("beam");
const e = @import("erl_nif");
const std = @import("std");

fn get_tuple(comptime T: type, term: beam.term) !T {
    const info = @typeInfo(T);
    const fields = info.Struct.fields;

    var arity: c_int = undefined;
    var ptr: [*c]const e.ErlNifTerm = undefined;
    if (e.enif_get_tuple(beam.context.env, term.v, &arity, &ptr) == 0) return error.ArgumentError;
    if (arity != fields.len) return error.ArgumentError;

    var result: T = undefined;
    inline for (fields, 0..) |field, i| {
        if (field.type == f64) {
            var val: f64 = undefined;
            if (e.enif_get_double(beam.context.env, ptr[i], &val) != 0) {
                @field(result, field.name) = val;
            } else {
                var ival: i64 = undefined;
                if (e.enif_get_int64(beam.context.env, ptr[i], &ival) != 0) {
                    @field(result, field.name) = @as(f64, @floatFromInt(ival));
                } else return error.ArgumentError;
            }
        } else {
            @field(result, field.name) = try beam.get(field.type, .{ .v = ptr[i] }, .{});
        }
    }
    return result;
}

pub fn create0_nif() beam.term {
    return beam.make(.{ 0.0, 0.0, 0.0 }, .{});
}

pub fn create3_nif(x: f64, y: f64, z: f64) beam.term {
    return beam.make(.{ x, y, z }, .{});
}

pub fn create1_nif(vec: beam.term) !beam.term {
    var list = vec.v;
    var head: e.ErlNifTerm = undefined;
    var x: f64 = undefined;
    var y: f64 = undefined;
    var z: f64 = undefined;

    if (e.enif_get_list_cell(beam.context.env, list, &head, &list) == 0) return error.ArgumentError;
    if (e.enif_get_double(beam.context.env, head, &x) == 0) {
        var ix: i64 = undefined;
        if (e.enif_get_int64(beam.context.env, head, &ix) == 0) return error.ArgumentError;
        x = @as(f64, @floatFromInt(ix));
    }

    if (e.enif_get_list_cell(beam.context.env, list, &head, &list) == 0) return error.ArgumentError;
    if (e.enif_get_double(beam.context.env, head, &y) == 0) {
        var iy: i64 = undefined;
        if (e.enif_get_int64(beam.context.env, head, &iy) == 0) return error.ArgumentError;
        y = @as(f64, @floatFromInt(iy));
    }

    if (e.enif_get_list_cell(beam.context.env, list, &head, &list) == 0) return error.ArgumentError;
    if (e.enif_get_double(beam.context.env, head, &z) == 0) {
        var iz: i64 = undefined;
        if (e.enif_get_int64(beam.context.env, head, &iz) == 0) return error.ArgumentError;
        z = @as(f64, @floatFromInt(iz));
    }

    return beam.make(.{ x, y, z }, .{});
}

pub fn add_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    return beam.make(.{ a.@"0" + b.@"0", a.@"1" + b.@"1", a.@"2" + b.@"2" }, .{});
}

pub fn subtract_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    return beam.make(.{ a.@"0" - b.@"0", a.@"1" - b.@"1", a.@"2" - b.@"2" }, .{});
}

pub fn multiply_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    return beam.make(.{ a.@"0" * b.@"0", a.@"1" * b.@"1", a.@"2" * b.@"2" }, .{});
}

pub fn scale_nif(a_term: beam.term, s: f64) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    return beam.make(.{ a.@"0" * s, a.@"1" * s, a.@"2" * s }, .{});
}

pub fn dot_nif(a_term: beam.term, b_term: beam.term) !f64 {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    return a.@"0" * b.@"0" + a.@"1" * b.@"1" + a.@"2" * b.@"2";
}

pub fn cross_nif(a_term: beam.term, b_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    return beam.make(.{
        a.@"1" * b.@"2" - a.@"2" * b.@"1",
        a.@"2" * b.@"0" - a.@"0" * b.@"2",
        a.@"0" * b.@"1" - a.@"1" * b.@"0",
    }, .{});
}

pub fn length_nif(a_term: beam.term) !f64 {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    return std.math.sqrt(a.@"0" * a.@"0" + a.@"1" * a.@"1" + a.@"2" * a.@"2");
}

pub fn length_squared_nif(a_term: beam.term) !f64 {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    return a.@"0" * a.@"0" + a.@"1" * a.@"1" + a.@"2" * a.@"2";
}

pub fn length_manhattan_nif(a_term: beam.term) !f64 {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    return a.@"0" + a.@"1" + a.@"2";
}

pub fn normalize_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const invmag = 1.0 / std.math.sqrt(a.@"0" * a.@"0" + a.@"1" * a.@"1" + a.@"2" * a.@"2");
    return beam.make(.{ a.@"0" * invmag, a.@"1" * invmag, a.@"2" * invmag }, .{});
}

pub fn lerp_nif(a_term: beam.term, b_term: beam.term, t: f64) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    return beam.make(.{
        t * b.@"0" + (1.0 - t) * a.@"0",
        t * b.@"1" + (1.0 - t) * a.@"1",
        t * b.@"2" + (1.0 - t) * a.@"2",
    }, .{});
}

pub fn near_nif(a_term: beam.term, b_term: beam.term, distance: f64) !bool {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    const dx = a.@"0" - b.@"0";
    const dy = a.@"1" - b.@"1";
    const dz = a.@"2" - b.@"2";
    return distance > std.math.sqrt(dx * dx + dy * dy + dz * dz);
}

pub fn equal_nif(a_term: beam.term, b_term: beam.term) !bool {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    return a.@"0" == b.@"0" and a.@"1" == b.@"1" and a.@"2" == b.@"2";
}

pub fn equal_eps_nif(a_term: beam.term, b_term: beam.term, eps: f64) !bool {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    return @abs(a.@"0" - b.@"0") <= eps and @abs(a.@"1" - b.@"1") <= eps and @abs(a.@"2" - b.@"2") <= eps;
}

pub fn negate_nif(a_term: beam.term) !beam.term {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    return beam.make(.{ -a.@"0", -a.@"1", -a.@"2" }, .{});
}

pub fn weighted_sum_nif(a: f64, v1_term: beam.term, b: f64, v2_term: beam.term) !beam.term {
    const v1 = try get_tuple(struct { f64, f64, f64 }, v1_term);
    const v2 = try get_tuple(struct { f64, f64, f64 }, v2_term);
    return beam.make(.{ a * v1.@"0" + b * v2.@"0", a * v1.@"1" + b * v2.@"1", a * v1.@"2" + b * v2.@"2" }, .{});
}

pub fn scalar_triple_nif(a_term: beam.term, b_term: beam.term, c_term: beam.term) !f64 {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    const c = try get_tuple(struct { f64, f64, f64 }, c_term);
    return a.@"0" * (b.@"1" * c.@"2" - b.@"2" * c.@"1") +
        a.@"1" * (b.@"2" * c.@"0" - b.@"0" * c.@"2") +
        a.@"2" * (b.@"0" * c.@"1" - b.@"1" * c.@"0");
}

pub fn minkowski_distance_nif(a_term: beam.term, b_term: beam.term, order: f64) !f64 {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    const adx = @abs(b.@"0" - a.@"0");
    const ady = @abs(b.@"1" - a.@"1");
    const adz = @abs(b.@"2" - a.@"2");
    const temp = std.math.pow(f64, adx, order) + std.math.pow(f64, ady, order) + std.math.pow(f64, adz, order);
    return std.math.pow(f64, temp, 1.0 / order);
}

pub fn chebyshev_distance_nif(a_term: beam.term, b_term: beam.term) !f64 {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const b = try get_tuple(struct { f64, f64, f64 }, b_term);
    const adx = @abs(b.@"0" - a.@"0");
    const ady = @abs(b.@"1" - a.@"1");
    const adz = @abs(b.@"2" - a.@"2");
    return @max(adx, @max(ady, adz));
}

pub fn p_norm_nif(a_term: beam.term, order: f64) !f64 {
    const a = try get_tuple(struct { f64, f64, f64 }, a_term);
    const ax = @abs(a.@"0");
    const ay = @abs(a.@"1");
    const az = @abs(a.@"2");
    const temp = std.math.pow(f64, ax, order) + std.math.pow(f64, ay, order) + std.math.pow(f64, az, order);
    return std.math.pow(f64, temp, 1.0 / order);
}
